
BLENDER="C:\Program Files\Blender Foundation\Blender 3.3\blender.exe"
DIST=../dist

all : \
    $(DIST)/dolphin.pnct \
    $(DIST)/dolphin.scene \

$(DIST)/dolphin.scene : dolphin.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "dolphin.blend:Main" "$(DIST)/dolphin.scene"

$(DIST)/dolphin.pnct : dolphin.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "dolphin.blend:Main" "$(DIST)/dolphin.pnct" 
