
BLENDER="C:\Program Files\Blender Foundation\Blender 3.3\blender.exe"
DIST=../dist

all : \
    $(DIST)/brunch.pnct \
    $(DIST)/brunch.scene \

$(DIST)/brunch.scene : brunch.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "brunch.blend:Main" "$(DIST)/brunch.scene"

$(DIST)/brunch.pnct : brunch.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "brunch.blend:Main" "$(DIST)/brunch.pnct" 
